ctx_params={}

ctx_params['S1']={
    'structure_info': {
        'region_name': "S1",
        'region_size': [1., 1., 1.366],
        'layer_thickness': [0.128, 0.056, 0.235, 0.207, 0.107, 0.273, 0.360],
        'layer_depth': [0, 0.128, 0.184, 0.419, 0.626, 0.733, 1.006, 1.366],
        'Layer_Name': ['L1', 'L2', 'L3', 'L4', 'L5A', 'L5B', 'L6'],
        'Layer_Cellcount_mm2': [4575.334,3270.034,16693.623,21268.353,5631.072,14903.491,27734.67]
        },
    'neuro_info': {
        'L1': {
            'SBC': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "E_ex" : 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "Cellcount_mm2": 3019.72044
                },
            'ENGC': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 1555.61356
                }
            },
        'L2': {
            'Pyr': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "E",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 2714.12822
                },
            'PV': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 160.5344711
                },
            'SST': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 64.19044042
                },
            'VIP': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 331.1808684
                }
            },
        'L3': {
            'Pyr': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "E",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 15191.19693
                },
            'PV': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 433.8706005
                },
            'SST': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 173.4851383},
            'VIP': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 895.0703312
                }
            },
        'L4': {
            'Pyr': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "E",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 19545.61641
                },
            'PV': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 1364.873436
                },
            'SST': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 357.863157
                }
            },
        'L5A': {
            'Pyr': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "E",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 4510.488672
                },
            'PV': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 710.7989056
                },
            'SST': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 409.7844224
                }
            },
        'L5B': {
            'Pyr': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "E",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 12489.12546
                },
            'PV': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 1301.725431},
            'SST': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 1112.640111
                }
            },
        'L6': {
            'Pyr': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "E",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 25072.14168
                },
            'PV': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 10.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 1533.281691},
            'SST': {
                "neuron_model": "iaf_cond_alpha",
                "EorI": "I",
                "membrane_time_constant": 20.0,
                "spike_threshold": -50.0,
                "reset_value": -70.0,
                "E_rest": -70.0,
                "I_ex": 0.0,
                "E_ex": 0.0,
                "E_in": -80.,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33,
                "absolute_refractory_period": 1.0,
                "Cellcount_mm2": 1129.246629
                }
            }
        },
    'connection_info': {
        'internal': 'S1_internal_connection.pickle'
        }
    }

ctx_params['M1']={
    "connection_info": {
        "internal": "M1_internal_connection.json"
        },
    "neuro_info": {
        "L1": {
            "ENGC": {
                "Cellcount_mm2": 611.9966,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 10.0,
                "n_type_index": 1,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "SBC": {
                "Cellcount_mm2": 1187.9934,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 10.0,
                "n_type_index": 0,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                }
            },
        "L23": {
            "CC": {
                "Cellcount_mm2": 14659.2,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "E",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 0,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "PV": {
                "Cellcount_mm2": 1256.83,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 10.0,
                "n_type_index": 1,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "SST": {
                "Cellcount_mm2": 1113.13,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 2,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "VIP": {
                "Cellcount_mm2": 1291.18,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 10.0,
                "n_type_index": 3,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                }
            },
        "L5A": {
            "CC": {
                "Cellcount_mm2": 1702.0327,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "E",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 1,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "CS": {
                "Cellcount_mm2": 1702.0327,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "E",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 0,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "CT": {
                    "Cellcount_mm2": 1702.0327,
                    "E_ex": 0.0,
                    "E_in": -80.0,
                    "E_rest": -70.0,
                    "EorI": "E",
                    "I_ex": 0.0,
                    "absolute_refractory_period": 1.0,
                    "membrane_time_constant": 20.0,
                    "n_type_index": 2,
                    "neuron_model": "iaf_cond_alpha",
                    "reset_value": -70.0,
                    "spike_threshold": -50.0,
                    "tau_syn_ex": 0.5,
                    "tau_syn_in": 3.33
                },
            "PV": {
                "Cellcount_mm2": 638.26,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 10.0,
                "n_type_index": 3,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "SST": {
                "Cellcount_mm2": 651.16,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 4,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                }
            },
        "L5B": {
            "CC": {
                "Cellcount_mm2": 3036.5812,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "E",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 2,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "CS": {
                "Cellcount_mm2": 3036.5812,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "E",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 1,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "PT": {
                "Cellcount_mm2": 6073.1624,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "E",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 0,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "PV": {
                "Cellcount_mm2": 1503.11,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 10.0,
                "n_type_index": 3,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "SST": {
                "Cellcount_mm2": 1533.47,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 4,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                }
            },
        "L6": {
            "CT": {
                "Cellcount_mm2": 14102.4,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "E",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 0,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "PV": {
                "Cellcount_mm2": 1393.55,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 10.0,
                "n_type_index": 1,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                },
            "SST": {
                "Cellcount_mm2": 2132.05,
                "E_ex": 0.0,
                "E_in": -80.0,
                "E_rest": -70.0,
                "EorI": "I",
                "I_ex": 0.0,
                "absolute_refractory_period": 1.0,
                "membrane_time_constant": 20.0,
                "n_type_index": 2,
                "neuron_model": "iaf_cond_alpha",
                "reset_value": -70.0,
                "spike_threshold": -50.0,
                "tau_syn_ex": 0.5,
                "tau_syn_in": 3.33
                }
            }
        },
    "position_type_info": {
        "L1": "M1_Neuron_pos_L1.npz",
        "L23": "M1_Neuron_pos_L23.npz",
        "L5A": "M1_Neuron_pos_L5A.npz",
        "L5B": "M1_Neuron_pos_L5B.npz",
        "L6": "M1_Neuron_pos_L6.npz"
        },
    "structure_info": {
        "Layer_Cellcount_mm2": [1799.99, 18320.334, 6395.5168, 15182.9, 17628.0],
        "Layer_Name": ["L1", "L23", "L5A", "L5B", "L6"],
        "layer_depth": [0.0, 0.14, 0.444, 0.644, 1.115, 1.4],
        "layer_thickness": [0.14, 0.304, 0.2, 0.471, 0.285],
        "region_name": "M1",
        "region_size": [1.0, 1.0, 1.4]
        }
    }
